[phases.setup]
nixPkgs = ["php82", "php82Packages.composer"]

[phases.install]
cmds = ["cd backend && composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = [
  "cd backend && mkdir -p database",
  "cd backend && touch database/database.sqlite"
]

[start]
cmd = "cd backend && php artisan migrate --force --seed && php artisan serve --host=0.0.0.0 --port=$PORT"
