[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs-20_x"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm ci --prefix ../frontend"
]

[phases.build]
cmds = [
  "npm run build --prefix ../frontend",
  "mkdir -p database",
  "touch database/database.sqlite"
]

[start]
cmd = "php artisan migrate --force --seed && php artisan serve --host=0.0.0.0 --port=$PORT"
